// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VirtaMatePackageManager.Infrastructure.Data;

#nullable disable

namespace VirtaMatePackageManager.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VirtaMatePackageManager.Core.Entities.ContentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContentType")
                        .HasColumnType("integer")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<bool>("IsPreset")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_preset");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("relative_path");

                    b.Property<string>("PreviewImagePath")
                        .HasColumnType("text")
                        .HasColumnName("preview_image_path");

                    b.Property<int>("VarPackageId")
                        .HasColumnType("integer")
                        .HasColumnName("var_package_id");

                    b.HasKey("Id");

                    b.HasIndex("ContentType")
                        .HasDatabaseName("idx_content_items_type");

                    b.HasIndex("VarPackageId")
                        .HasDatabaseName("idx_content_items_var_package");

                    b.HasIndex("VarPackageId", "Path")
                        .IsUnique()
                        .HasDatabaseName("uk_content_items_var_package_path");

                    b.ToTable("content_items", (string)null);
                });

            modelBuilder.Entity("VirtaMatePackageManager.Core.Entities.Dependency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DependencyName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("dependency_name");

                    b.Property<bool>("IsOptional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_optional");

                    b.Property<bool>("IsResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_resolved");

                    b.Property<int?>("ResolvedVarPackageId")
                        .HasColumnType("integer")
                        .HasColumnName("resolved_var_package_id");

                    b.Property<int>("VarPackageId")
                        .HasColumnType("integer")
                        .HasColumnName("var_package_id");

                    b.Property<string>("VersionConstraint")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("version_constraint");

                    b.HasKey("Id");

                    b.HasIndex("DependencyName")
                        .HasDatabaseName("idx_dependencies_name");

                    b.HasIndex("IsResolved")
                        .HasDatabaseName("idx_dependencies_resolved_flag");

                    b.HasIndex("ResolvedVarPackageId")
                        .HasDatabaseName("idx_dependencies_resolved");

                    b.HasIndex("VarPackageId")
                        .HasDatabaseName("idx_dependencies_var_package");

                    b.HasIndex("VarPackageId", "DependencyName")
                        .IsUnique()
                        .HasDatabaseName("uk_dependencies_var_package_name");

                    b.ToTable("dependencies", (string)null);
                });

            modelBuilder.Entity("VirtaMatePackageManager.Core.Entities.Installation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InstallationTargetId")
                        .HasColumnType("integer")
                        .HasColumnName("installation_target_id");

                    b.Property<DateTime>("InstalledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("installed_at");

                    b.Property<string>("InstalledBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("installed_by");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<string>("SymlinkPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symlink_path");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VarPackageId")
                        .HasColumnType("integer")
                        .HasColumnName("var_package_id");

                    b.HasKey("Id");

                    b.HasIndex("InstallationTargetId")
                        .HasDatabaseName("idx_installations_target");

                    b.HasIndex("InstalledAt")
                        .HasDatabaseName("idx_installations_installed_at");

                    b.HasIndex("SymlinkPath")
                        .IsUnique()
                        .HasDatabaseName("uk_installations_symlink_path");

                    b.HasIndex("VarPackageId")
                        .HasDatabaseName("idx_installations_var_package");

                    b.HasIndex("VarPackageId", "InstallationTargetId")
                        .IsUnique()
                        .HasDatabaseName("uk_installations_var_package_target");

                    b.ToTable("installations", (string)null);
                });

            modelBuilder.Entity("VirtaMatePackageManager.Core.Entities.InstallationTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<string>("ProfileName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("profile_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_installation_targets_active");

                    b.HasIndex("Path")
                        .IsUnique()
                        .HasDatabaseName("uk_installation_targets_path");

                    b.HasIndex("ProfileName")
                        .HasDatabaseName("idx_installation_targets_profile");

                    b.ToTable("installation_targets", (string)null);
                });

            modelBuilder.Entity("VirtaMatePackageManager.Core.Entities.Repository", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("priority");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Enabled")
                        .HasDatabaseName("idx_repositories_enabled")
                        .HasFilter("\"enabled\" = true");

                    b.HasIndex("Path")
                        .IsUnique()
                        .HasDatabaseName("uk_repositories_path");

                    b.HasIndex("Priority", "Enabled")
                        .HasDatabaseName("idx_repositories_priority");

                    b.ToTable("repositories", (string)null);
                });

            modelBuilder.Entity("VirtaMatePackageManager.Core.Entities.VarPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatorName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("creator_name");

                    b.Property<string>("Credits")
                        .HasColumnType("text")
                        .HasColumnName("credits");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("FileCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("file_created_at");

                    b.Property<string>("FileHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("file_hash");

                    b.Property<DateTime?>("FileModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("file_modified_at");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("Instructions")
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_scanned_at");

                    b.Property<string>("LicenseType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("license_type");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("package_name");

                    b.Property<string>("PreviewImagePath")
                        .HasColumnType("text")
                        .HasColumnName("preview_image_path");

                    b.Property<string>("ProgramVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("program_version");

                    b.Property<string>("PromotionalLink")
                        .HasColumnType("text")
                        .HasColumnName("promotional_link");

                    b.Property<string>("RelativePath")
                        .HasColumnType("text")
                        .HasColumnName("relative_path");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("integer")
                        .HasColumnName("repository_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VarName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("var_name");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CreatorName")
                        .HasDatabaseName("idx_var_packages_creator");

                    b.HasIndex("PackageName")
                        .HasDatabaseName("idx_var_packages_package");

                    b.HasIndex("RepositoryId")
                        .HasDatabaseName("idx_var_packages_repository");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("idx_var_packages_updated");

                    b.HasIndex("VarName")
                        .IsUnique()
                        .HasDatabaseName("uk_var_name");

                    b.HasIndex("Version")
                        .HasDatabaseName("idx_var_packages_version");

                    b.HasIndex("RepositoryId", "FilePath")
                        .IsUnique()
                        .HasDatabaseName("uk_var_package_repo_path");

                    b.HasIndex("CreatorName", "PackageName", "Version")
                        .HasDatabaseName("idx_var_packages_composite");

                    b.ToTable("var_packages", (string)null);
                });

            modelBuilder.Entity("VirtaMatePackageManager.Core.Entities.ContentItem", b =>
                {
                    b.HasOne("VirtaMatePackageManager.Core.Entities.VarPackage", "VarPackage")
                        .WithMany("ContentItems")
                        .HasForeignKey("VarPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VarPackage");
                });

            modelBuilder.Entity("VirtaMatePackageManager.Core.Entities.Dependency", b =>
                {
                    b.HasOne("VirtaMatePackageManager.Core.Entities.VarPackage", "ResolvedVarPackage")
                        .WithMany()
                        .HasForeignKey("ResolvedVarPackageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VirtaMatePackageManager.Core.Entities.VarPackage", "VarPackage")
                        .WithMany("Dependencies")
                        .HasForeignKey("VarPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResolvedVarPackage");

                    b.Navigation("VarPackage");
                });

            modelBuilder.Entity("VirtaMatePackageManager.Core.Entities.Installation", b =>
                {
                    b.HasOne("VirtaMatePackageManager.Core.Entities.InstallationTarget", "InstallationTarget")
                        .WithMany("Installations")
                        .HasForeignKey("InstallationTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirtaMatePackageManager.Core.Entities.VarPackage", "VarPackage")
                        .WithMany("Installations")
                        .HasForeignKey("VarPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InstallationTarget");

                    b.Navigation("VarPackage");
                });

            modelBuilder.Entity("VirtaMatePackageManager.Core.Entities.VarPackage", b =>
                {
                    b.HasOne("VirtaMatePackageManager.Core.Entities.Repository", "Repository")
                        .WithMany("VarPackages")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("VirtaMatePackageManager.Core.Entities.InstallationTarget", b =>
                {
                    b.Navigation("Installations");
                });

            modelBuilder.Entity("VirtaMatePackageManager.Core.Entities.Repository", b =>
                {
                    b.Navigation("VarPackages");
                });

            modelBuilder.Entity("VirtaMatePackageManager.Core.Entities.VarPackage", b =>
                {
                    b.Navigation("ContentItems");

                    b.Navigation("Dependencies");

                    b.Navigation("Installations");
                });
#pragma warning restore 612, 618
        }
    }
}
