// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VarVault.Infrastructure.Persistence;

#nullable disable

namespace VarVault.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VarVaultDbContext))]
    partial class VarVaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("VarVault.Domain.Entities.ActivationLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AliasedMissingRefKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("LinkKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LinkPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkSubfolder")
                        .HasColumnType("TEXT");

                    b.Property<int>("LinkType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reason")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RequestedByPresetId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("VarFileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("RequestedByPresetId");

                    b.HasIndex("VarFileId");

                    b.ToTable("ActivationLink", (string)null);
                });

            modelBuilder.Entity("VarVault.Domain.Entities.ActivityEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("PackageId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TimestampUnixMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUnixMs");

                    b.ToTable("ActivityEntry", (string)null);
                });

            modelBuilder.Entity("VarVault.Domain.Entities.Collection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRuleBased")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Collection", (string)null);
                });

            modelBuilder.Entity("VarVault.Domain.Entities.CollectionMember", b =>
                {
                    b.Property<long>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PackageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CollectionId", "PackageId");

                    b.HasIndex("PackageId");

                    b.ToTable("CollectionMember", (string)null);
                });

            modelBuilder.Entity("VarVault.Domain.Entities.ContentItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntryPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("GenderConfidence")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsPreset")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreviewThumbRef")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<long>("VarFileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.HasIndex("VarFileId");

                    b.ToTable("ContentItem", (string)null);
                });

            modelBuilder.Entity("VarVault.Domain.Entities.ContentItemPref", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContentItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContentItemId")
                        .IsUnique();

                    b.ToTable("ContentItemPref", (string)null);
                });

            modelBuilder.Entity("VarVault.Domain.Entities.Dependency", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DependsOnRefKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DependsOnRefRaw")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMissing")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVersionSubstituted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RefKind")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ResolvedPackageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResolvedVia")
                        .HasColumnType("INTEGER");

                    b.Property<long>("VarFileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnRefKey");

                    b.HasIndex("ResolvedPackageId");

                    b.HasIndex("VarFileId", "DependsOnRefKey")
                        .IsUnique();

                    b.ToTable("Dependency", (string)null);
                });

            modelBuilder.Entity("VarVault.Domain.Entities.DirtyPackage", b =>
                {
                    b.Property<long>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MarkedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PackageId");

                    b.HasIndex("MarkedAt");

                    b.ToTable("DirtyPackage", (string)null);
                });

            modelBuilder.Entity("VarVault.Domain.Entities.ImportFailedSourceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("ImportFailedSources");
                });

            modelBuilder.Entity("VarVault.Domain.Entities.ImportOutcomeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lane")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("ImportOutcomes");
                });

            modelBuilder.Entity("VarVault.Domain.Entities.ImportRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Copied")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Discarded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Failed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fixed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Renamed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Skipped")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetRepositoryId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ImportRuns");
                });

            modelBuilder.Entity("VarVault.Domain.Entities.LoadingPreset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRuleBased")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ProfileId");

                    b.ToTable("LoadingPreset", (string)null);
                });

            modelBuilder.Entity("VarVault.Domain.Entities.MigrationJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesCopied")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceRepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TargetRepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TempPath")
                        .HasColumnType("TEXT");

                    b.Property<long>("VarFileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VarFileId")
                        .IsUnique()
                        .HasFilter("\"State\" NOT IN (6, 7, 8)");

                    b.ToTable("MigrationJob", (string)null);
                });

            modelBuilder.Entity("VarVault.Domain.Entities.Package", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CanonicalVarFileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFoundational")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastIndexedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseType")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaCreator")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MetaDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MetaDivergent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetaPackage")
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgramVersion")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReverseDependentCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VarName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("VersionSort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VersionToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalVarFileId");

                    b.HasIndex("IdentityKey")
                        .IsUnique();

                    b.HasIndex("IsFavorite");

                    b.HasIndex("VarName")
                        .IsUnique();

                    b.HasIndex("Creator", "PackageName", "VersionSort");

                    b.ToTable("Package", (string)null);
                });

            modelBuilder.Entity("VarVault.Domain.Entities.PackageContentCount", b =>
                {
                    b.Property<long>("PackageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.HasKey("PackageId", "Type");

                    b.ToTable("PackageContentCount", (string)null);
                });

            modelBuilder.Entity("VarVault.Domain.Entities.PackageListItem", b =>
                {
                    b.Property<long>("PackageId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActualTierMin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Class")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasMissingDeps")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("InstalledAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSingleCopy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("OnlineInstanceCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewThumbRef")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrimaryType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalInstanceCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VarName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VersionToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PackageId");

                    b.HasIndex("HasMissingDeps");

                    b.HasIndex("IsFavorite");

                    b.HasIndex("PrimaryType", "VarName");

                    b.HasIndex("AddedAt", "VarName", "PackageId");

                    b.HasIndex("Class", "LastUsedAt", "PackageId");

                    b.HasIndex("Creator", "TotalSize", "PackageId");

                    b.HasIndex("InstalledAt", "VarName", "PackageId");

                    b.HasIndex("PackageId")
                        .HasFilter("IsActive = 1");

                    b.ToTable("PackageListItem", (string)null);
                });

            modelBuilder.Entity("VarVault.Domain.Entities.PackageTag", b =>
                {
                    b.Property<long>("PackageId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PackageId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PackageTag", (string)null);
                });

            modelBuilder.Entity("VarVault.Domain.Entities.PresetMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVersionSubstituted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PackageRefKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageRefRaw")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PresetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResolutionMode")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ResolvedPackageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResolvedVersion")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PresetId");

                    b.HasIndex("ResolvedPackageId");

                    b.HasIndex("PresetId", "PackageRefKey")
                        .IsUnique();

                    b.ToTable("PresetMember", (string)null);
                });

            modelBuilder.Entity("VarVault.Domain.Entities.Profile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Profile", (string)null);
                });

            modelBuilder.Entity("VarVault.Domain.Entities.ProfilePackageLink", b =>
                {
                    b.Property<long>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PackageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InstalledAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Reason")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ProfileId", "PackageId");

                    b.HasIndex("PackageId");

                    b.HasIndex("ProfileId", "InstalledAt");

                    b.ToTable("ProfilePackageLink", (string)null);
                });

            modelBuilder.Entity("VarVault.Domain.Entities.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BenchmarkedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CapacityBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FreeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MinFreeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MountPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PriorityInTier")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ReadSpeedMBps")
                        .HasColumnType("REAL");

                    b.Property<int>("Tier")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VolumeSerial")
                        .HasColumnType("TEXT");

                    b.Property<double?>("WriteSpeedMBps")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("MountPath");

                    b.HasIndex("Tier");

                    b.ToTable("Repository", (string)null);
                });

            modelBuilder.Entity("VarVault.Domain.Entities.SaveDependency", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DependsOnRefKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DependsOnRefRaw")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMissing")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ResolvedPackageId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserSaveId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnRefKey");

                    b.HasIndex("ResolvedPackageId");

                    b.HasIndex("UserSaveId", "DependsOnRefKey")
                        .IsUnique();

                    b.ToTable("SaveDependency", (string)null);
                });

            modelBuilder.Entity("VarVault.Domain.Entities.ScanRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Discovered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<long>("Failed")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Ingested")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Phase")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Pruned")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SigFileCount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SigNewestMtimeTicks")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SigPathsHash")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SigTotalBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Skipped")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Phase");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("RepositoryId", "Generation");

                    b.ToTable("ScanRun", (string)null);
                });

            modelBuilder.Entity("VarVault.Domain.Entities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Setting", (string)null);
                });

            modelBuilder.Entity("VarVault.Domain.Entities.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NameKey")
                        .IsUnique();

                    b.ToTable("Tag", (string)null);
                });

            modelBuilder.Entity("VarVault.Domain.Entities.TrashItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Bytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("PackageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrashPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TrashedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.ToTable("TrashItem", (string)null);
                });

            modelBuilder.Entity("VarVault.Domain.Entities.UsageEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PackageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TimestampUnixMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PackageId", "TimestampUnixMs");

                    b.ToTable("UsageEvent", (string)null);
                });

            modelBuilder.Entity("VarVault.Domain.Entities.UsageStat", b =>
                {
                    b.Property<long>("PackageId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CentralityScore")
                        .HasColumnType("REAL");

                    b.Property<int>("Class")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsForcedCold")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPinnedHot")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastFlipAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("RolledUpUseCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<string>("ScoreHistory")
                        .HasColumnType("TEXT");

                    b.Property<int>("Use30d")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Use90d")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UseCountTotal")
                        .HasColumnType("INTEGER");

                    b.HasKey("PackageId");

                    b.HasIndex("Class");

                    b.ToTable("UsageStat", (string)null);
                });

            modelBuilder.Entity("VarVault.Domain.Entities.UserSave", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Mtime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("UserSave", (string)null);
                });

            modelBuilder.Entity("VarVault.Domain.Entities.VarAlias", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MissingRefKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MissingRefRaw")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("PresetId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ResolvedPackageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResolvedVarName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MissingRefKey");

                    b.HasIndex("PresetId");

                    b.HasIndex("ResolvedPackageId");

                    b.ToTable("VarAlias", (string)null);
                });

            modelBuilder.Entity("VarVault.Domain.Entities.VarFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrokenEntryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentSignature")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentSignatureNoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedCodepage")
                        .HasColumnType("TEXT");

                    b.Property<int>("EncodingHealth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FileMtime")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FixedFromVarFileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IndexedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IngestAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IngestError")
                        .HasColumnType("TEXT");

                    b.Property<int>("IngestState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntegrityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LeaseExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LeaseOwner")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PackageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadSignature")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuarantineKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuickHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<long>("SeenGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SupersededByVarFileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .HasFilter("\"ContentHash\" IS NOT NULL");

                    b.HasIndex("ContentSignature");

                    b.HasIndex("ContentSignatureNoPath");

                    b.HasIndex("FixedFromVarFileId");

                    b.HasIndex("PackageId");

                    b.HasIndex("PayloadSignature");

                    b.HasIndex("SupersededByVarFileId");

                    b.HasIndex("IngestState", "LeaseExpiresAt");

                    b.HasIndex("RepositoryId", "RelativePath")
                        .IsUnique();

                    b.HasIndex("RepositoryId", "SeenGeneration");

                    b.ToTable("VarFile", (string)null);
                });

            modelBuilder.Entity("VarVault.Domain.Entities.ActivationLink", b =>
                {
                    b.HasOne("VarVault.Domain.Entities.Profile", "Profile")
                        .WithMany("Links")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VarVault.Domain.Entities.LoadingPreset", "RequestedByPreset")
                        .WithMany()
                        .HasForeignKey("RequestedByPresetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VarVault.Domain.Entities.VarFile", "VarFile")
                        .WithMany()
                        .HasForeignKey("VarFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("RequestedByPreset");

                    b.Navigation("VarFile");
                });

            modelBuilder.Entity("VarVault.Domain.Entities.CollectionMember", b =>
                {
                    b.HasOne("VarVault.Domain.Entities.Collection", "Collection")
                        .WithMany("Members")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VarVault.Domain.Entities.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("VarVault.Domain.Entities.ContentItem", b =>
                {
                    b.HasOne("VarVault.Domain.Entities.VarFile", "VarFile")
                        .WithMany("ContentItems")
                        .HasForeignKey("VarFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VarFile");
                });

            modelBuilder.Entity("VarVault.Domain.Entities.ContentItemPref", b =>
                {
                    b.HasOne("VarVault.Domain.Entities.ContentItem", "ContentItem")
                        .WithMany()
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentItem");
                });

            modelBuilder.Entity("VarVault.Domain.Entities.Dependency", b =>
                {
                    b.HasOne("VarVault.Domain.Entities.Package", "ResolvedPackage")
                        .WithMany()
                        .HasForeignKey("ResolvedPackageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VarVault.Domain.Entities.VarFile", "VarFile")
                        .WithMany("Dependencies")
                        .HasForeignKey("VarFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResolvedPackage");

                    b.Navigation("VarFile");
                });

            modelBuilder.Entity("VarVault.Domain.Entities.ImportFailedSourceEntity", b =>
                {
                    b.HasOne("VarVault.Domain.Entities.ImportRunEntity", "Run")
                        .WithMany("FailedSources")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("VarVault.Domain.Entities.ImportOutcomeEntity", b =>
                {
                    b.HasOne("VarVault.Domain.Entities.ImportRunEntity", "Run")
                        .WithMany("Outcomes")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("VarVault.Domain.Entities.LoadingPreset", b =>
                {
                    b.HasOne("VarVault.Domain.Entities.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("VarVault.Domain.Entities.MigrationJob", b =>
                {
                    b.HasOne("VarVault.Domain.Entities.VarFile", "VarFile")
                        .WithMany()
                        .HasForeignKey("VarFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VarFile");
                });

            modelBuilder.Entity("VarVault.Domain.Entities.Package", b =>
                {
                    b.HasOne("VarVault.Domain.Entities.VarFile", "CanonicalVarFile")
                        .WithMany()
                        .HasForeignKey("CanonicalVarFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CanonicalVarFile");
                });

            modelBuilder.Entity("VarVault.Domain.Entities.PackageContentCount", b =>
                {
                    b.HasOne("VarVault.Domain.Entities.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("VarVault.Domain.Entities.PackageListItem", b =>
                {
                    b.HasOne("VarVault.Domain.Entities.Package", "Package")
                        .WithOne()
                        .HasForeignKey("VarVault.Domain.Entities.PackageListItem", "PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("VarVault.Domain.Entities.PackageTag", b =>
                {
                    b.HasOne("VarVault.Domain.Entities.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VarVault.Domain.Entities.Tag", "Tag")
                        .WithMany("PackageTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("VarVault.Domain.Entities.PresetMember", b =>
                {
                    b.HasOne("VarVault.Domain.Entities.LoadingPreset", "Preset")
                        .WithMany("Members")
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VarVault.Domain.Entities.Package", "ResolvedPackage")
                        .WithMany()
                        .HasForeignKey("ResolvedPackageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Preset");

                    b.Navigation("ResolvedPackage");
                });

            modelBuilder.Entity("VarVault.Domain.Entities.ProfilePackageLink", b =>
                {
                    b.HasOne("VarVault.Domain.Entities.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VarVault.Domain.Entities.Profile", "Profile")
                        .WithMany("PackageLinks")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("VarVault.Domain.Entities.SaveDependency", b =>
                {
                    b.HasOne("VarVault.Domain.Entities.Package", "ResolvedPackage")
                        .WithMany()
                        .HasForeignKey("ResolvedPackageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VarVault.Domain.Entities.UserSave", "UserSave")
                        .WithMany("Dependencies")
                        .HasForeignKey("UserSaveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResolvedPackage");

                    b.Navigation("UserSave");
                });

            modelBuilder.Entity("VarVault.Domain.Entities.TrashItem", b =>
                {
                    b.HasOne("VarVault.Domain.Entities.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Package");
                });

            modelBuilder.Entity("VarVault.Domain.Entities.UsageEvent", b =>
                {
                    b.HasOne("VarVault.Domain.Entities.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("VarVault.Domain.Entities.UsageStat", b =>
                {
                    b.HasOne("VarVault.Domain.Entities.Package", "Package")
                        .WithOne()
                        .HasForeignKey("VarVault.Domain.Entities.UsageStat", "PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("VarVault.Domain.Entities.VarAlias", b =>
                {
                    b.HasOne("VarVault.Domain.Entities.LoadingPreset", "Preset")
                        .WithMany()
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VarVault.Domain.Entities.Package", "ResolvedPackage")
                        .WithMany()
                        .HasForeignKey("ResolvedPackageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Preset");

                    b.Navigation("ResolvedPackage");
                });

            modelBuilder.Entity("VarVault.Domain.Entities.VarFile", b =>
                {
                    b.HasOne("VarVault.Domain.Entities.VarFile", "FixedFromVarFile")
                        .WithMany()
                        .HasForeignKey("FixedFromVarFileId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("VarVault.Domain.Entities.Package", "Package")
                        .WithMany("VarFiles")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VarVault.Domain.Entities.Repository", "Repository")
                        .WithMany("VarFiles")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VarVault.Domain.Entities.VarFile", "SupersededByVarFile")
                        .WithMany()
                        .HasForeignKey("SupersededByVarFileId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("FixedFromVarFile");

                    b.Navigation("Package");

                    b.Navigation("Repository");

                    b.Navigation("SupersededByVarFile");
                });

            modelBuilder.Entity("VarVault.Domain.Entities.Collection", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("VarVault.Domain.Entities.ImportRunEntity", b =>
                {
                    b.Navigation("FailedSources");

                    b.Navigation("Outcomes");
                });

            modelBuilder.Entity("VarVault.Domain.Entities.LoadingPreset", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("VarVault.Domain.Entities.Package", b =>
                {
                    b.Navigation("VarFiles");
                });

            modelBuilder.Entity("VarVault.Domain.Entities.Profile", b =>
                {
                    b.Navigation("Links");

                    b.Navigation("PackageLinks");
                });

            modelBuilder.Entity("VarVault.Domain.Entities.Repository", b =>
                {
                    b.Navigation("VarFiles");
                });

            modelBuilder.Entity("VarVault.Domain.Entities.Tag", b =>
                {
                    b.Navigation("PackageTags");
                });

            modelBuilder.Entity("VarVault.Domain.Entities.UserSave", b =>
                {
                    b.Navigation("Dependencies");
                });

            modelBuilder.Entity("VarVault.Domain.Entities.VarFile", b =>
                {
                    b.Navigation("ContentItems");

                    b.Navigation("Dependencies");
                });
#pragma warning restore 612, 618
        }
    }
}
