<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\VarVault.Common\VarVault.Common.csproj" />
    <ProjectReference Include="..\..\src\VarVault.Sdk\VarVault.Sdk.csproj" />
    <ProjectReference Include="..\..\src\VarVault.Domain\VarVault.Domain.csproj" />
    <ProjectReference Include="..\..\src\VarVault.Infrastructure\VarVault.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\VarVault.Host\VarVault.Host.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.Testing" />
  </ItemGroup>
</Project>
